# Site settings
email: yuzhi.hu@anu.edu.au
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: "UA-87277449-1"

# SEO settings
title: ls -h Yuzhi & Ernu
description: 
url: ""
twitter_username: Daisyhu24
default_img: 

# Profile settings
name: Yuzhi Daisy Hu
profile_img: assets/image/profile.jpg
profile: I am a PHD student at the Australian National Universtiy. I do paleontology, but I also have passion in fashion, food and animals.
social:
  github: https://github.com/yuzhihu

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
exclude: [vendor]
